const softwareData = [
  {
    name: "Flax",
    type: "Neural Network",
    repo: "https://github.com/google/flax",
    stars: 3000,
    dependencies: ["jax"],
    status: "Active",
  },
  {
    name: "Haiku",
    type: "Neural Network",
    repo: "https://github.com/deepmind/haiku",
    stars: 2800,
    dependencies: ["jax"],
    status: "Inactive",
  },
  {
    name: "Equinox",
    type: "Neural Network",
    repo: "https://github.com/patrick-kidger/equinox",
    stars: 1800,
    dependencies: ["jax"],
    status: "2025-01-25",
  },
  {
    name: "Brax",
    type: "RL Environment",
    repo: "https://github.com/google/brax",
    stars: 2000,
    dependencies: ["jax"],
    status: "2025-02-05",
  },
  {
    name: "Gymnax",
    type: "RL Environment",
    repo: "https://github.com/RobertTLange/gymnax",
    stars: 500,
    dependencies: ["jax"],
    status: "2025-01-20",
  },
  {
    name: "Jumanji",
    type: "RL Environment",
    repo: "https://github.com/instadeepai/jumanji",
    stars: 700,
    dependencies: ["jax"],
    status: "2025-02-07",
  },
  {
    name: "BlackJAX",
    type: "Inference / Sampling",
    repo: "https://github.com/blackjax-devs/blackjax",
    stars: 350,
    dependencies: ["equinox", "jax"],
    status: "2025-01-31",
  },

  // Extra made-up items
  {
    name: "awesome",
    type: "Neural Network",
    repo: "https://github.com/mhlr/awesome-jax",
    stars: 999,
    dependencies: ["pytorch"],
    status: "2024-12-12",
  },
  {
    name: "BlueRL",
    type: "RL Environment",
    repo: "https://github.com/fake/blue-rl",
    stars: 123,
    dependencies: ["numpy", "jax"],
    status: "2025-01-15",
  },
  {
    name: "VioletSampler",
    type: "Inference / Sampling",
    repo: "https://github.com/fake/violet-sampler",
    stars: 42,
    dependencies: ["blackjax", "jax"],
    status: "2024-11-05",
  },
  {
    name: "OrangeX",
    type: "Neural Network",
    repo: "https://github.com/fake/orange-x",
    stars: 2500,
    dependencies: ["jax", "numpy"],
    status: "2025-02-02",
  },
  {
    name: "NeonBandit",
    type: "RL Environment",
    repo: "https://github.com/fake/neon-bandit",
    stars: 75,
    dependencies: ["numpy"],
    status: "2025-01-28",
  },
  {
    name: "QuantumNet",
    type: "Neural Network",
    repo: "https://github.com/fake/quantum-net",
    stars: 888,
    dependencies: ["jax", "flax"],
    status: "2025-01-18",
  },
  {
    name: "ZetaMonteCarlo",
    type: "Inference / Sampling",
    repo: "https://github.com/fake/zeta-monte-carlo",
    stars: 202,
    dependencies: ["equinox"],
    status: "2025-01-05",
  },
  {
    name: "OmegaEnv",
    type: "RL Environment",
    repo: "https://github.com/fake/omega-env",
    stars: 555,
    dependencies: ["gymnax", "jax"],
    status: "2025-02-03",
  },
  {
    name: "DeltaModel",
    type: "Neural Network",
    repo: "https://github.com/fake/delta-model",
    stars: 1200,
    dependencies: ["numpy", "scipy"],
    status: "2024-12-25",
  },
];
